  socials: [
    { src: './docs/assets/youtube.svg', height: '25px', width: '25px' },
    { src: './docs/assets/whatsapp.svg', height: '25px', width: '25px' },
    { src: './docs/assets/upwork.svg', height: '25px', width: '25px' },
    { src: './docs/assets/soundcloud.svg', height: '25px', width: '25px' },
    { src: './docs/assets/linkedin.svg', height: '25px', width: '25px' },
    { src: './docs/assets/kickstarter.svg', height: '25px', width: '25px' },
  ],
  languages: [
    { src: './docs/assets/clojure.svg', height: '25px', width: '25px' },
    { src: './docs/assets/css3.svg', height: '25px', width: '25px' },
    { src: './docs/assets/deno.svg', height: '25px', width: '25px' },
    { src: './docs/assets/discord.svg', height: '25px', width: '25px' },
    { src: './docs/assets/go.svg', height: '25px', width: '25px' },
    { src: './docs/assets/java.svg', height: '25px', width: '25px' },
  ],
  skills: [
    { src: './docs/assets/astro.svg', height: '25px', width: '25px' },
    { src: './docs/assets/bun.svg', height: '25px', width: '25px' },
    { src: './docs/assets/python.svg', height: '25px', width: '25px' },
    { src: './docs/assets/npm.svg', height: '25px', width: '25px' },
    { src: './docs/assets/javascript.svg', height: '25px', width: '25px' },
    { src: './docs/assets/facebook.svg', height: '25px', width: '25px' },
  ],